language: node_js
node_js:
- lts/*
jobs:
  include:
  - stage: release
    node_js: lts/carbon
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
env:
  global:
  - secure: L6RU9t8/iD6wFeNjHR8HiMVxepcMbzaRSgqPigjJtWogVKILAmdKzLCp+HKZBI5u5b1CEMyO7JTxFRHdXrWZP0jc/9tF6o3y04KHN3xQB9fcp6ancYKuM1+YS3kQfOes+gQn0nbj9mo+F5yXnVWk+GGevs7CcTwbgIM7t96gGKam811TgkKcOJ3Et+O43f+cgS/FJBLDvHz3riOSW/+Ct8tGqm8L4+jeVYwxNfLgfFrUmxdgHvPjBnJODyEz0LdOjVJqEk3sjkP8SYYlpHG6ZtQl3UpudS5mHNRXJjOx5oQB5CFl/HGNAn/dcWBREdeIpbPfTBPNN1dIChIQLnObSTHfyg8LPH+ZQVErdN5xy3+4aPNYxqPu1IWoIGJVJ3WZufvR2OA46LP9CfzFD+4LZNrmpv6eFz7++yIRlb3C5sgHFVWLLMTtPugMNTVtHu8MK3+TIqfvNQt3qi15+6xv4K4Yhrcn1hEnDmkt7ZcRf8gr8xEwizNKrGvwjsOnD+6AR48yp/6rm7G8lq/CaVxshvyirtjdp+r+H4TfEVtDqGw1oLgiGnlCsYlrmQOvt0KxHr02vfJa6yxne7QNvWcSi3y1iw0GWqqhC92s4LSJaiRyk53pgLa2pQPbCSrOmfKC5xCl4E0hdmQfJ7YEas5c+XQ0FdgNPWSSbFLdRWPjCAs=
  - secure: ul4sV1kngTDn1/2/525qBg7Eim6ntGFWSEJcWnKX3aqL7fGEnLu9M859y0Q6Bq6aVazgRbgNOmTZ1t5VuJzHiO1HE7N1WVpJlHnyKqtNoHiRb6bEC/rrR5MT4jXeaoiprp3ybkjmIzcW+LhHwpzGTFar/xZjdaklE++CmlTCxMV3vcrXOhqCz59ffNVcrLpAb+9n5jwfyTPvqLg2kU4TQzKpckC3GROQjoByorxyjbB/9PZYC+kK5xsURrYmZL9m10YUJccNgWbb1BduCcF4lHeOljOr9+lZ/lygKvcKD248Y2DvSjnFpr6Q/eXHQxRPQIdRmGpfA6UvQZJQ6gSkkJT/DY9AGt1mDKJBVBy3k336kKv203X8tKceKynL4qvv/zEzOhFoV3rAoWS1ZqLTFg1OSX2SZFRxMovZkG8akz3jo7WL59AN/MzczMCW8RtXyjDhttwSgnpsV+bwiFVWuU05p0NOPj/hszztCbQVzbWNCAjm5BLGfSRylc/5MSmhUgLw1VHm9WBTbW8sjPFG7jIwNRjEAEYb5hPEXJoxA95rsti4tMGexYmv23WKC8K+9riwNt87DwUcKOVYbLFoaWRH2GrnIV2g54Mr/4asTtd+Mq9IgvaAsZs2UD3gRXYT1DYWBn/tWDSnKf/28GfXCGr7zO3QY7gDqcnJi0IQYOM=
